name: Test and Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./src/Gerenciamento.Funcionarios/Gerenciamento.Funcionarios.sln

    - name: Verify runsettings exists
      run: |
        ls -la src/Gerenciamento.Funcionarios/Gerenciamento.Funcionarios.Tests/
        cat src/Gerenciamento.Funcionarios/Gerenciamento.Funcionarios.Tests/coverlet.runsettings.xml
      
    - name: Run tests with coverage
      working-directory: src/Gerenciamento.Funcionarios/Gerenciamento.Funcionarios.Tests
      run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings.xml --logger trx

    - name: Check coverage
      uses: irongut/CodeCoverageSummary@v1.3.0 
      with:
        filename: '**/coverage.cobertura.xml'
        badge: true
        fail_below_min: true
        minimum_coverage: 80
        format: markdown