name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Run tests
      working-directory: src/Gerenciamento.Funcionarios/Gerenciamento.Funcionarios.Tests
      run: |
        dotnet test --no-build --logger trx